name: Example-project
on: 
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: print the comment
        run: echo "hello my name is Venkata Amarnath"
    
  
